version: "3.9"
services:
  h_mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
     - 3306:3306
    image: mysql:8.1.0
    container_name: mysql810
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - h_mysql
    environment:
        PMA_USER: ${PMA_USER}
        PMA_PASSWORD: ${PMA_PASSWORD}
        PMA_ARBITRARY: 1
        PMA_HOSTS: h_mysql
        UPLOAD_LIMIT: 512M
    ports:
      - "18080:80"
    volumes:
      - ./volumes/phpmyadmin/sessions:/sessions
      - ./volumes/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
volumes:
  mysql_data:
  mysql_logs:

# Following config to .env
# MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
# MYSQL_DATABASE: ${MYSQL_DATABASE}
# MYSQL_USER: ${MYSQL_USER}
# MYSQL_PASSWORD: ${MYSQL_PASSWORD}
# PMA_USER: ${PMA_USER}
# PMA_PASSWORD: ${PMA_PASSWORD}
